### ISSUE TITLE
require_once(C:\wamp\www\examples): failed to open stream: Permission denied in C:\wamp\www\examples\example.php on line 4

### ISSUE THREAD

**Issue by eKivOxhd** [ChristianChoi/thetvdb-api#1]
Hello ,

You maybe forget a file ? 
// Load composer dependencies
require_once realpath(__DIR__.'/../vendor/autoload.php');

Where is it ? Thank you

**Comment by ChristianChoi** [comment]
Hi Arthur,
The package requires a few external packages, through Composer (https://getcomposer.org/).
If you don't have Composer already, donwload it and run the following command in your command line:
```
composer update
```

This should make Composer download the required dependencies, which is loaded into your project by including the file **vendor/autoload.php**

I hope this helps.

**Comment by eKivOxhd** [comment]
Hello , tell me it's possible to get the Next-AirDate ?Thx
